#!/bin/bash
################################## !!! README !!! #######################################
#                                                                                       #
# Script name: kodi                                                        #
# Tested on Ubuntu 20.04 - Ubuntu 22.04                                     #
# chmod the script                                                                      #
# then load it simply typing: sudo ./kodi_installer                                  #
#                                                                                       #
#########################################################################################

clear
while :
do
    dialog --title "   ** Install & Setup KODI **   " --infobox "

   --------------------------------------------------------------

        [a]    Install Kodi
        [b]    Remove Kodi

        [z]    Exit

   -------------------------------------------------------------- " 0 0

echo -n "        Enter your menu choice = Install [a] ~~ Remove [b] ~~ Exit [z]:      "
read yourch
case $yourch in

a)
clear
apt-get -y install software-properties-common pkg-config

clear
    dialog --title "   ** KODI **   " --infobox "
   ----------------------------------------------
                KODI versions
   ----------------------------------------------
  
        [a]    Kodi Stable version
        [b]    Kodi Release Candidate version
        
    " 0 0
    echo -n "        Enter your menu choice  [a-z]:      "
    read yourch
    case $yourch in

a)   clear; add-apt-repository ppa:team-xbmc/ppa; apt-get update; apt-get -y install kodi; apt-get -y install kodi-pvr-iptvsimple; apt-get install kodi-pvr-vdr-vnsi; apt-mark hold kodi;;
b)   clear; add-apt-repository ppa:team-xbmc/unstable; apt-get update;  apt-get -y install kodi; apt-get -y install kodi-pvr-iptvsimple; apt-get install kodi-pvr-vdr-vnsi; apt-mark hold kodi;;
esac
#
echo "                    *** Install Kill Kodi Icon ***"
sleep 2
cd /usr/local/bin
rm -rf /usr/local/bin/Killkodi.sh
touch /usr/local/bin/Killkodi.sh
echo '#!/bin/sh

killall -9 /usr/lib/x86_64-linux-gnu/kodi/kodi.bin && sudo /etc/init.d/server-vdr stop > /dev/null 2>&1 
# & killall -9 oscam & shutdown -h now '  >> /usr/local/bin/Killkodi.sh
chmod 777 /usr/local/bin/Killkodi.sh
#
echo "                    *** Setup Kill Kodi icon  ***"
sleep 1
rm -rf /home/`logname`/Scrivania/Killkodi.desktop
rm -rf /usr/share/applications/Killkodi.desktop
touch /usr/share/applications/Killkodi.desktop
echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=KillKodi
Description=Kill Kodi
Icon=$SRC/icone/killkodi.png
Exec=/usr/local/bin/Killkodi.sh
" >> /usr/share/applications/Killkodi.desktop
chmod 777 /usr/share/applications/Killkodi.desktop
#
echo "                    *** Install Kodi Picon ***"
sleep 1
cp -rf /home/'logname'/Vdr-repo/kodi_picon.tar.gz $ETC
cd $ETC
tar -zxvf kodi_picon.tar.gz
rm -rf kodi_picon.tar.gz
#
echo "                    *** Install Kodi  Lircmap ***"
# lsb_release -a
dmesg | grep -i 20.04 > $TEMP/release_check
if cat $TEMP/release_check | grep "20.04"; 
then echo "Ubuntu 20.04 detected" 
cd /usr/share/kodi/system
rm -rf Lircmap.xml
cp -rf /home/'logname'/Vdr-repo/Lircmap_Kodi.tar.gz /usr/share/kodi/system
tar -zxvf Lircmap_Kodi.tar.gz
rm -rf Lircmap_Kodi.tar.gz
else echo "Ubuntu 22.04 detected"
fi
rm -rf $TEMP/release_check  
#
cd $REPO/
chmod -R 777 *

echo "                    Press Enter to continue ...               "
read enterKey;;


#############################################################

b)

clear
echo "                    Remove KODI"
sleep 2
rm -rf ~/.kodi/
rm -rf /home/`logname`/.kodi/*
rm -rf /usr/share/kodi
add-apt-repository --remove ppa:team-xbmc/ppa -y
add-apt-repository --remove ppa:team-xbmc/unstable -y
rm -rf /home/`logname`/Scrivania/Kodi.desktop
rm -rf /usr/share/applications/Kodi.desktop;;
#
z)
clear  
exit 0;;
#
*) ;;
esac
done
